# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\WinPython-64bit-3.4.4.5Qt5\QtUiFiles\LocalViewNewUser.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(630, 363)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.hostIdListView = QtWidgets.QListView(self.centralwidget)
        self.hostIdListView.setMinimumSize(QtCore.QSize(299, 192))
        self.hostIdListView.setObjectName("hostIdListView")
        self.verticalLayout.addWidget(self.hostIdListView)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.newUserLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.newUserLineEdit.setObjectName("newUserLineEdit")
        self.horizontalLayout.addWidget(self.newUserLineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.siteIdListView = QtWidgets.QListView(self.centralwidget)
        self.siteIdListView.setMinimumSize(QtCore.QSize(299, 192))
        self.siteIdListView.setObjectName("siteIdListView")
        self.verticalLayout_2.addWidget(self.siteIdListView)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.userRoleGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.userRoleGroupBox.setMaximumSize(QtCore.QSize(16777215, 53))
        self.userRoleGroupBox.setObjectName("userRoleGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.userRoleGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.adminRadioButton = QtWidgets.QRadioButton(self.userRoleGroupBox)
        self.adminRadioButton.setObjectName("adminRadioButton")
        self.horizontalLayout_2.addWidget(self.adminRadioButton)
        self.userRadioButton = QtWidgets.QRadioButton(self.userRoleGroupBox)
        self.userRadioButton.setObjectName("userRadioButton")
        self.horizontalLayout_2.addWidget(self.userRadioButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.userRoleGroupBox)
        self.isGroupGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.isGroupGroupBox.setObjectName("isGroupGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.isGroupGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupTrueRadioButton = QtWidgets.QRadioButton(self.isGroupGroupBox)
        self.groupTrueRadioButton.setObjectName("groupTrueRadioButton")
        self.gridLayout_2.addWidget(self.groupTrueRadioButton, 0, 0, 1, 1)
        self.groupFalseRadioButton = QtWidgets.QRadioButton(self.isGroupGroupBox)
        self.groupFalseRadioButton.setObjectName("groupFalseRadioButton")
        self.gridLayout_2.addWidget(self.groupFalseRadioButton, 0, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.isGroupGroupBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.addUserPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.addUserPushButton.setMinimumSize(QtCore.QSize(90, 23))
        self.addUserPushButton.setMaximumSize(QtCore.QSize(90, 23))
        self.addUserPushButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.addUserPushButton.setObjectName("addUserPushButton")
        self.gridLayout_3.addWidget(self.addUserPushButton, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 630, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Host ids:"))
        self.label_3.setText(_translate("MainWindow", "New User:"))
        self.label_2.setText(_translate("MainWindow", "Site ids:"))
        self.userRoleGroupBox.setTitle(_translate("MainWindow", "User Role:"))
        self.adminRadioButton.setText(_translate("MainWindow", "Administrator"))
        self.userRadioButton.setText(_translate("MainWindow", "User"))
        self.isGroupGroupBox.setTitle(_translate("MainWindow", "Is Group:"))
        self.groupTrueRadioButton.setText(_translate("MainWindow", "True"))
        self.groupFalseRadioButton.setText(_translate("MainWindow", "False"))
        self.addUserPushButton.setText(_translate("MainWindow", "Add User"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

